# DO NOT EDIT THIS FILE -- Muro auto-generated file
{% if helpers.exists('Muro.monit.general.enabled') and Muro.monit.general.enabled|default("0") == "1" %}
monit_setup="/usr/local/opnsense/scripts/Muro/Monit/setup.sh"
monit_enable="YES"
{% else %}
monit_enable="NO"
{% endif %}
