#
# Automatic generated configuration for netflow.
# Do not edit this file manually.
#
{%
  if helpers.exists('Muro.Netflow.capture.interfaces')
  and
  Muro.Netflow.capture.interfaces.strip()
  and
  Muro.Netflow.capture.targets.strip()%}
netflow_enable="YES"
{% else %}
netflow_enable="NO"
{% endif %}
